# Generated by Django 5.2.5 on 2025-09-11 16:57

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='nome completo', max_length=50, verbose_name='nome')),
                ('fone', models.CharField(help_text='Número do telefone', max_length=15, verbose_name='fone')),
                ('email', models.CharField(help_text='Endereço de Email', max_length=100, unique=True, verbose_name='email')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='pessoa', variations={}, verbose_name='foto')),
                ('funcao', models.CharField(help_text='Função na Empresa', max_length=35, verbose_name='Função')),
                ('data_admissao', models.DateField(help_text='Data de admissão na empresa', verbose_name='Admissao')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
    ]
